# Generated by Django 4.2.16 on 2026-04-03 07:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de prompts',
                'verbose_name_plural': 'Categorias de prompts',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HashtagPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Hashtag de prompt',
                'verbose_name_plural': 'Hashtags de prompts',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion breve del prompt y para que sirve.')),
                ('contenido', models.TextField(help_text='El texto del prompt. Usa {nombre_variable} para partes rellenables.')),
                ('variables_json', models.JSONField(blank=True, default=list, help_text='Definicion de variables: [{"nombre": "tema", "descripcion": "El tema a tratar", "valor_defecto": "marketing"}]')),
                ('visibilidad', models.CharField(choices=[('publico', 'Publico total'), ('semipublico', 'Semipublico'), ('privado', 'Privado - membresia premium')], default='publico', max_length=20)),
                ('publicado', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('publicado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='prompts.categoriaprompt')),
                ('hashtags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.hashtagprompt')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['-destacado', '-publicado_en'],
            },
        ),
        migrations.CreateModel(
            name='ValoracionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='prompts.prompt')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoracion de prompt',
                'verbose_name_plural': 'Valoraciones de prompts',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='prompts.categoriaprompt')),
            ],
            options={
                'verbose_name': 'Subcategoria de prompts',
                'verbose_name_plural': 'Subcategorias de prompts',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PromptFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='prompts.prompt')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt favorito',
                'verbose_name_plural': 'Prompts favoritos',
                'ordering': ['-agregado_en'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='prompts.subcategoriaprompt'),
        ),
        migrations.AddConstraint(
            model_name='valoracionprompt',
            constraint=models.UniqueConstraint(fields=('usuario', 'prompt'), name='uniq_valoracion_prompt_usuario_prompt'),
        ),
        migrations.AddConstraint(
            model_name='subcategoriaprompt',
            constraint=models.UniqueConstraint(fields=('categoria', 'slug'), name='uniq_subcategoria_prompt_categoria_slug'),
        ),
        migrations.AddConstraint(
            model_name='promptfavorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'prompt'), name='uniq_favorito_prompt_usuario_prompt'),
        ),
    ]
