# Generated by Django 4.2.16 on 2026-04-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_seed_prompt_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='imagen_muestra',
            field=models.ImageField(blank=True, help_text='Imagen de muestra del resultado (opcional, para prompts de imagen).', null=True, upload_to='prompts/muestras/'),
        ),
    ]
