# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia', to=settings.AUTH_USER_MODEL),
        ),
    ]
