# Generated by Django 4.2.16 on 2026-04-07 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curriculum Vitae',
                'verbose_name_plural': 'Curriculums Vitae',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=200, verbose_name='Puesto')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('trabajo_actual', models.BooleanField(default=False, verbose_name='Trabajo actual')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Responsabilidades')),
                ('logros', models.TextField(blank=True, verbose_name='Logros')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
                'ordering': ['orden', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.CharField(max_length=200, verbose_name='Organización')),
                ('funcion', models.CharField(max_length=200, verbose_name='Función / Rol')),
                ('impacto', models.TextField(blank=True, verbose_name='Impacto')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('en_curso', models.BooleanField(default=False, verbose_name='En curso')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteerings', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Voluntariado',
                'verbose_name_plural': 'Voluntariados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('portfolio', models.URLField(blank=True, verbose_name='Portfolio / Web personal')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('otras', models.CharField(blank=True, max_length=500, verbose_name='Otras redes (describe)')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Redes profesionales',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hard', 'Hard Skill (técnica)'), ('soft', 'Soft Skill (blanda)')], default='hard', max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(blank=True, choices=[('lenguaje', 'Lenguaje de programación'), ('framework', 'Framework / Librería'), ('herramienta', 'Herramienta'), ('otro', 'Otro'), ('', 'Sin categoría')], max_length=20, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=100, verbose_name='Habilidad')),
                ('nivel', models.PositiveSmallIntegerField(blank=True, help_text='1=Básico, 5=Experto', null=True, verbose_name='Nivel (1–5)')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['tipo', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tecnologias', models.CharField(blank=True, max_length=300, verbose_name='Tecnologías usadas')),
                ('link', models.URLField(blank=True, verbose_name='Enlace (GitHub / web)')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=200, verbose_name='Profesión / Especialidad')),
                ('objetivo', models.CharField(blank=True, max_length=300, verbose_name='Objetivo profesional')),
                ('resumen', models.TextField(verbose_name='Resumen profesional')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Perfil profesional',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('telefono1', models.CharField(max_length=30, verbose_name='Teléfono 1')),
                ('telefono2', models.CharField(blank=True, max_length=30, verbose_name='Teléfono 2')),
                ('email_profesional1', models.EmailField(max_length=254, verbose_name='Email profesional 1')),
                ('email_profesional2', models.EmailField(blank=True, max_length=254, verbose_name='Email profesional 2')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad')),
                ('carnet_conducir', models.BooleanField(default=False, verbose_name='Carnet de conducir')),
                ('disponibilidad', models.CharField(choices=[('inmediata', 'Inmediata'), ('parcial', 'Parcial'), ('por_acordar', 'Por acordar'), ('no_disponible', 'No disponible')], default='inmediata', max_length=20, verbose_name='Disponibilidad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='curriculum/fotos/', verbose_name='Foto')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Datos personales',
            },
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad_viajar', models.BooleanField(default=False, verbose_name='Disponibilidad para viajar')),
                ('teletrabajo', models.CharField(choices=[('si', 'Sí, 100% remoto'), ('parcial', 'Teletrabajo parcial'), ('no', 'Presencial'), ('indiferente', 'Indiferente')], default='indiferente', max_length=20, verbose_name='Disponibilidad de teletrabajo')),
                ('expectativa_salarial', models.CharField(blank=True, max_length=200, verbose_name='Expectativas salariales')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Otros datos',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100, verbose_name='Idioma')),
                ('nivel', models.CharField(choices=[('nativo', 'Nativo'), ('C2', 'C2 – Maestría'), ('C1', 'C1 – Dominio operativo eficaz'), ('B2', 'B2 – Avanzado'), ('B1', 'B1 – Intermedio'), ('A2', 'A2 – Básico'), ('A1', 'A1 – Principiante')], max_length=10, verbose_name='Nivel')),
                ('certificacion', models.CharField(blank=True, max_length=200, verbose_name='Certificación')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Interés')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Interés',
                'verbose_name_plural': 'Intereses',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('centro', models.CharField(max_length=200, verbose_name='Centro educativo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('en_curso', models.BooleanField(default=False, verbose_name='En curso')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Formación académica',
                'verbose_name_plural': 'Formaciones académicas',
                'ordering': ['orden', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ComplementaryTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('certificacion', 'Certificación'), ('bootcamp', 'Bootcamp'), ('taller', 'Taller'), ('otro', 'Otro')], default='curso', max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('entidad', models.CharField(blank=True, max_length=200, verbose_name='Entidad / Institución')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción breve')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Formación complementaria',
                'verbose_name_plural': 'Formaciones complementarias',
                'ordering': ['orden', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Descripción')),
                ('tipo', models.CharField(choices=[('premio', 'Premio'), ('merito', 'Mérito académico'), ('evento', 'Participación en evento'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Detalle')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='curriculum.curriculumvitae')),
            ],
            options={
                'verbose_name': 'Logro / Reconocimiento',
                'verbose_name_plural': 'Logros y reconocimientos',
                'ordering': ['orden', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: "Desarrollador Frontend", "Data Analyst"', max_length=200, verbose_name='Nombre del perfil')),
                ('slug', models.SlugField(help_text='Ej: OscarBurgos_frontend → opentowork.es/OscarBurgos_frontend', max_length=100, verbose_name='URL slug')),
                ('template', models.CharField(choices=[('minimalist', 'Minimalista'), ('tech', 'Tech (VSCode style)'), ('normal', 'Clásico')], default='minimalist', max_length=20, verbose_name='Plantilla')),
                ('is_public', models.BooleanField(default=True, verbose_name='Perfil público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mostrar_perfil_profesional', models.BooleanField(default=True, verbose_name='Mostrar perfil profesional')),
                ('mostrar_redes', models.BooleanField(default=True, verbose_name='Mostrar redes sociales')),
                ('mostrar_intereses', models.BooleanField(default=True, verbose_name='Mostrar intereses')),
                ('mostrar_otros', models.BooleanField(default=False, verbose_name='Mostrar otros datos')),
                ('mostrar_voluntariado', models.BooleanField(default=True, verbose_name='Mostrar voluntariado')),
                ('mostrar_logros', models.BooleanField(default=True, verbose_name='Mostrar logros')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='curriculum.curriculumvitae')),
                ('educaciones', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.education', verbose_name='Formación académica')),
                ('experiencias', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.workexperience', verbose_name='Experiencias')),
                ('formaciones', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.complementarytraining', verbose_name='Formación complementaria')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.skill', verbose_name='Habilidades')),
                ('idiomas', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.language', verbose_name='Idiomas')),
                ('intereses', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.interest', verbose_name='Intereses')),
                ('logros', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.achievement', verbose_name='Logros')),
                ('proyectos', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.project', verbose_name='Proyectos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_profiles', to=settings.AUTH_USER_MODEL)),
                ('voluntariados', models.ManyToManyField(blank=True, related_name='profiles', to='curriculum.volunteering', verbose_name='Voluntariados')),
            ],
            options={
                'verbose_name': 'Perfil de CV',
                'verbose_name_plural': 'Perfiles de CV',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
