# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaaprendizaje',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ruta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='resultadoquiz',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='courses.pregunta'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.tema'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='courses.tema'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='courses.curso'),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('usuario', 'tema')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioncurso',
            unique_together={('usuario', 'curso')},
        ),
    ]
