# Generated by Django 4.2.16 on 2026-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tipocurso_curso_horas_duracion_curso_tipo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='csv_filename',
            field=models.CharField(blank=True, help_text='Nombre del CSV dentro de static/quiz (ej: 0201QZ.csv).', max_length=255),
        ),
    ]
