# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='insignias/')),
                ('tipo', models.CharField(choices=[('curso', 'Completar Curso'), ('tema', 'Completar Tema'), ('streak', 'Racha'), ('puntos', 'Puntos Acumulados'), ('mision', 'Completar Misión'), ('especial', 'Especial')], max_length=20)),
                ('requisito_valor', models.PositiveIntegerField(default=0, help_text='Valor numérico del requisito (p.ej. racha de 7 días, 500 puntos, etc.)')),
                ('visible', models.BooleanField(default=True, help_text='Falso = insignia oculta/sorpresa')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'ordering': ['tipo', 'requisito_valor'],
            },
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insignia de Usuario',
                'verbose_name_plural': 'Insignias de Usuarios',
                'ordering': ['-fecha_obtenida'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntos_recompensa', models.PositiveIntegerField(default=50)),
                ('oculto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal')], max_length=10)),
                ('puntos_recompensa', models.PositiveIntegerField(default=30)),
                ('requisito_tipo', models.CharField(choices=[('completar_temas', 'Completar temas'), ('quiz_aprobado', 'Aprobar quizzes'), ('racha_dias', 'Mantener racha de días'), ('puntos_ganados', 'Ganar puntos')], max_length=30)),
                ('requisito_cantidad', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
            },
        ),
        migrations.CreateModel(
            name='MisionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignada', models.DateField(auto_now_add=True)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gamification.mision')),
            ],
            options={
                'verbose_name': 'Misión de Usuario',
                'verbose_name_plural': 'Misiones de Usuarios',
                'ordering': ['completada', '-fecha_asignada'],
            },
        ),
    ]
