# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='misionusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logrousuario',
            name='logro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.logro'),
        ),
        migrations.AddField(
            model_name='logrousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_obtenidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logro',
            name='insignia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros', to='gamification.insignia'),
        ),
        migrations.AddField(
            model_name='insigniausuario',
            name='insignia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.insignia'),
        ),
        migrations.AddField(
            model_name='insigniausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_obtenidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='logrousuario',
            unique_together={('usuario', 'logro')},
        ),
        migrations.AlterUniqueTogether(
            name='insigniausuario',
            unique_together={('usuario', 'insignia')},
        ),
    ]
