# Generated by Django 4.2.16 on 2026-03-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='curso_objetivo',
            field=models.ForeignKey(blank=True, help_text='Curso específico que activa esta insignia (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insignias_asociadas', to='courses.curso'),
        ),
        migrations.AddField(
            model_name='insignia',
            name='tema_objetivo',
            field=models.ForeignKey(blank=True, help_text='Tema específico que activa esta insignia (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insignias_asociadas', to='courses.tema'),
        ),
    ]
