# Generated by Django 4.2.16 on 2026-03-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_insignia_curso_objetivo_insignia_tema_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrousuario',
            name='puntos_asignados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
