# Generated by Django 4.2.16 on 2026-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_logrousuario_puntos_asignados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='puntos_recompensa',
            field=models.IntegerField(default=30),
        ),
    ]
