# Generated by Django 4.2.16 on 2026-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puntos_totales',
            field=models.IntegerField(default=0, help_text='Puntos acumulados históricos (nunca decrementan)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='puntos',
            field=models.IntegerField(default=0, help_text='Saldo canjeables actual'),
        ),
    ]
