# Generated by Django 4.2.16 on 2026-03-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_csv_filename'),
        ('users', '0002_user_puntos_totales_alter_user_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='courses.curso', verbose_name='Nombre del curso'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
