# Generated by Django 4.2.16 on 2026-03-27 09:02

from django.db import migrations, models


def recalcular_niveles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    niveles = [
        ('noob', 0),
        ('youngling', 100),
        ('padawan', 250),
        ('caballero_codigo', 500),
        ('maestro_codigo', 900),
        ('gran_maestro_jedi', 1500),
    ]

    for user in User.objects.all().only('id', 'puntos_totales', 'nivel'):
        nuevo_nivel = 'noob'
        for nivel, umbral in niveles:
            if user.puntos_totales >= umbral:
                nuevo_nivel = nivel
        if user.nivel != nuevo_nivel:
            user.nivel = nuevo_nivel
            user.save(update_fields=['nivel'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_curso_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(choices=[('noob', 'Noob'), ('youngling', 'Youngling'), ('padawan', 'Padawan'), ('caballero_codigo', 'Caballero del codigo'), ('maestro_codigo', 'Maestro del codigo'), ('gran_maestro_jedi', 'Gran Maestro Jedi')], default='noob', max_length=20),
        ),
        migrations.RunPython(recalcular_niveles, migrations.RunPython.noop),
    ]
