# Generated by Django 4.2.16 on 2026-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_curso_alter_user_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aula',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aula'),
        ),
    ]
