# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recompensas/')),
                ('puntos_necesarios', models.PositiveIntegerField()),
                ('stock', models.IntegerField(default=-1, help_text='-1 = stock ilimitado')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['puntos_necesarios'],
            },
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('puntos_gastados', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('notas_admin', models.TextField(blank=True)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='rewards.recompensa')),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
                'ordering': ['-fecha_canje'],
            },
        ),
    ]
