# Generated by Django 4.2.16 on 2026-04-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='alcance_tipo',
            field=models.CharField(choices=[('--- Módulo ---', (('MODULO', 'Módulo Formativo (bloque principal de competencias)'),)), ('--- Unidad Formativa ---', (('UF', 'Unidad Formativa — UF (división acreditable)'),)), ('--- Unidad Didáctica / Tema ---', (('UD', 'Unidad Didáctica (organización de temas y actividades)'), ('TEMA', 'Tema concreto'))), ('--- Evaluación ---', (('CAPACIDAD', 'Capacidad (objetivo: qué debe saber hacer el alumno)'), ('CRITERIO', 'Criterio de Evaluación (indicador medible)')))], max_length=15),
        ),
    ]
