# Generated by Django 4.2.16 on 2026-04-24 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tiporecursotema_alter_temarecurso_tipo_recurso'),
        ('evaluations', '0002_alcance_choices_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_uf', to='courses.curso', verbose_name='Curso (Unidad Formativa)'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='evaluaciones_modulo', to='courses.curso', verbose_name='Cursos (Módulo Formativo)'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='modulo_ref',
            field=models.CharField(blank=True, help_text='Referencia externa opcional del módulo (código, nombre externo…).', max_length=100),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='courses.tema', verbose_name='Tema (UD / Tema / Capacidad / Criterio)'),
        ),
    ]
