# Generated by Django 4.2.16 on 2026-04-24 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_tiporecursotema_alter_temarecurso_tipo_recurso'),
        ('users', '0009_user_role'),
        ('evaluations', '0003_add_curso_fk_cursos_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='correccionevaluacion',
            name='fecha_revision_docente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correccionevaluacion',
            name='observaciones_docente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='correccionevaluacion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_docentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correccionevaluacion',
            name='tipo_correccion',
            field=models.CharField(choices=[('IA', 'Automatica por IA'), ('DOCENTE_EXHAUSTIVA', 'Revision exhaustiva docente')], default='IA', max_length=20),
        ),
        migrations.AddField(
            model_name='entregaevaluacion',
            name='motivo_revision_exhaustiva',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entregaevaluacion',
            name='solicita_revision_exhaustiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='users.aula'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='criterios_evaluacion_pdf',
            field=models.FileField(blank=True, upload_to='evaluaciones/criterios/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='enunciado_pdf',
            field=models.FileField(blank=True, upload_to='evaluaciones/enunciados/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_prueba',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='rubrica_pdf',
            field=models.FileField(blank=True, upload_to='evaluaciones/rubricas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_prueba',
            field=models.CharField(choices=[('OBJ_TEST', 'Objetiva tipo test'), ('OBJ_REDACCION', 'Objetiva tipo redaccion'), ('PRACTICO_CODIGO', 'Practico tipo creacion de codigo'), ('PRACTICO_REDACCION', 'Practico tipo redaccion')], default='OBJ_TEST', max_length=20),
        ),
        migrations.AlterField(
            model_name='entregaevaluacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de correccion'), ('PROCESANDO', 'Procesando'), ('CORREGIDA', 'Corregida'), ('REVISION_DOCENTE', 'Revision docente'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='alcance_tipo',
            field=models.CharField(choices=[('UD', 'UD - Unidad Didactica'), ('UF', 'UF - Unidad Formativa'), ('MF', 'MF - Modulo Formativo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='enunciado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='courses.tema', verbose_name='Tema (UD)'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='evaluations.tipoexamen'),
        ),
    ]
