# Generated by Django 4.2.16 on 2026-04-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_rewrite_evaluations_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('DEFAULT', 'Por defecto (cualquier tipo)'), ('OBJ_TEST', 'Objetiva tipo test'), ('OBJ_REDACCION', 'Objetiva tipo redaccion'), ('PRACTICO_CODIGO', 'Practico tipo codigo'), ('PRACTICO_REDACCION', 'Practico tipo redaccion')], default='DEFAULT', max_length=25, verbose_name='Aplica a')),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('descripcion', models.TextField(blank=True, help_text='Notas internas sobre este prompt (cambios, razon, etc.).')),
                ('system_prompt', models.TextField(verbose_name='Prompt de sistema')),
                ('activo', models.BooleanField(default=False, help_text='Solo un prompt activo por scope. Al activar este se desactivan los demas del mismo scope.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt de correccion',
                'verbose_name_plural': 'Prompts de correccion',
                'ordering': ['scope', '-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='correccionevaluacion',
            name='prompt_sistema_usado',
            field=models.TextField(blank=True),
        ),
    ]
