# Generated by Django 4.2.16 on 2026-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_add_prompt_correccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='clave_respuestas',
            field=models.JSONField(blank=True, default=None, help_text='Solo para tests objetivos (OBJ_TEST). Diccionario JSON con la clave de corrección: {"1":"D","2":"C","3":"A",...}. Si se rellena, la puntuación se calcula en Python de forma exacta (aciertos × valor − errores × penalización) sin depender de la IA.', null=True),
        ),
    ]
