# Generated by Django 4.2.16 on 2026-03-27 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('comentario', models.TextField(help_text='Comentario visible para los usuarios')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enlace importante',
                'verbose_name_plural': 'Enlaces importantes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AccesoEnlaceUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accedido_en', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='enlaces.enlaceimportante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_enlaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a enlace',
                'verbose_name_plural': 'Accesos a enlaces',
                'ordering': ['-accedido_en'],
                'unique_together': {('usuario', 'enlace')},
            },
        ),
    ]
