# Generated by Django 4.2.16 on 2026-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceimportante',
            name='categoria',
            field=models.CharField(default='General', max_length=80),
        ),
    ]
