# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acceso', 'Acceso al sistema'), ('tema_completado', 'Tema completado'), ('quiz_completado', 'Quiz completado'), ('insignia_obtenida', 'Insignia obtenida'), ('recompensa_canjeada', 'Recompensa canjeada'), ('mision_completada', 'Misión completada')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos_ganados', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
    ]
