# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['usuario', 'tipo'], name='analytics_r_usuario_bd2e20_idx'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['-timestamp'], name='analytics_r_timesta_1ec999_idx'),
        ),
    ]
