# Generated by Django 4.2.16 on 2026-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='tipo',
            field=models.CharField(choices=[('acceso', 'Acceso al sistema'), ('tema_completado', 'Tema completado'), ('quiz_completado', 'Quiz completado'), ('recurso_visualizado', 'Recurso visualizado'), ('insignia_obtenida', 'Insignia obtenida'), ('recompensa_canjeada', 'Recompensa canjeada'), ('mision_completada', 'Misión completada')], max_length=30),
        ),
    ]
