# Generated by Django 4.2.16 on 2026-04-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_registroactividad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='tipo',
            field=models.CharField(choices=[('acceso', 'Acceso al sistema'), ('tema_completado', 'Tema completado'), ('quiz_completado', 'Quiz completado'), ('recurso_visualizado', 'Recurso visualizado'), ('insignia_obtenida', 'Insignia obtenida'), ('recompensa_canjeada', 'Recompensa canjeada'), ('mision_completada', 'Misión completada'), ('cv_seccion', 'Sección de CV completada'), ('bug_validado', 'Bug validado')], max_length=30),
        ),
    ]
