# Generated by Django 4.2.16 on 2026-03-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='courses.curso'),
        ),
    ]
